apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      # how the deployment will find the pods that actually creates
      app: orders-mongo
  template:
    metadata:
      # labels that applied to the pod
      labels:
        app: orders-mongo
    spec:
      containers:
        - name: orders-mongo
          # refer to mango image in docker hub
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: orders-mongo-srv
spec:
  selector:
    app: orders-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
